const MeetingState = {
    topic: '',
    uuid: '',
    meetingId: 0,
    password: '',
    hostEmail: '',
    status: '',
    startUrl: '',
    joinUrl: '',
    trainer: {
        id: '',
        trainerProfile: '',
        createdAt: new Date(),
        updatedAt: new Date(),
        type: 'trainer',
        user: {
            id: '',
            email: '',
            avatarUrl: '',
            name: '',
            username: '',
            roles: [],
            type: 'user',
        },
        classes: [
            {
                id: '',
                name: '',
                description: '',
                featuredImage: '',
                startTime: new Date(),
                endTime: null,
                duration: 0,
                createdAt: new Date(),
                updatedAt: new Date(),
                type: 'classe',
            },
        ],
    },
    agenda: null,
    startTime: null,
    endTime: null,
    duration: null,
    totalMinutes: null,
    participantsCount: null,
    source: null,
    id: '',
    createdAt: new Date(),
    updatedAt: new Date(),
    type: 'meeting',
};

export default MeetingState;
